package com.example.worldofraces.client.gui;

import com.example.worldofraces.WorldOfRaces;
import com.example.worldofraces.client.menu.ProfessionMenu;
import com.example.worldofraces.profession.NpcProfession;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractButton;
import net.minecraft.client.gui.narration.NarrationElementOutput;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

public final class ProfessionScreen extends AbstractContainerScreen<ProfessionMenu>{
    private static final ResourceLocation FRAME=new ResourceLocation(WorldOfRaces.MODID,"textures/gui/npc_menu_frame.png");private static final int W=640,H=360,TW=1672,TH=941,GOLD=0xFFF0D08A,TEXT=0xFFE8E2D8,MUTED=0xFFAAA79F;private float scale=1;
    public ProfessionScreen(ProfessionMenu m,Inventory i,Component t){super(m,i,t);imageWidth=W;imageHeight=H;titleLabelY=inventoryLabelY=-1000;}
    @Override protected void init(){super.init();leftPos=(width-W)/2;topPos=(height-H)/2;scale=Math.min(1,Math.min((width-16F)/W,(height-16F)/H));int y=96;for(NpcProfession p:NpcProfession.values()){PButton b=button(194,y,150,18,p.name,p.ordinal(),p==menu.snapshot().selected());if(!p.implemented&&p!=NpcProfession.NONE)b.active=true;y+=20;}var s=menu.snapshot();if(s.current()==NpcProfession.NONE)button(382,278,150,25,"Atribuir profissao",ProfessionMenu.ASSIGN,false).active=s.selected().implemented;else button(382,278,150,25,"Remover profissao",ProfessionMenu.REMOVE,false);button(80,216,104,25,"Equipamento",ProfessionMenu.EQUIPMENT,false);button(545,37,26,24,"X",-1,false);}
    private PButton button(int x,int y,int w,int h,String text,int action,boolean selected){PButton b=new PButton(leftPos+x,topPos+y,w,h,Component.literal(text),()->{if(action<0)onClose();else send(action);},selected);addRenderableWidget(b);return b;}private void send(int a){if(minecraft!=null&&minecraft.gameMode!=null)minecraft.gameMode.handleInventoryButtonClick(menu.containerId,a);}
    @Override protected void renderBg(GuiGraphics g,float pt,int mx,int my){g.blit(FRAME,leftPos,topPos,W,H,0,0,TW,TH,TW,TH);panel(g,194,88,150,228);panel(g,352,88,212,228);g.pose().pushPose();g.pose().translate(leftPos+145,topPos+40,0);g.pose().scale(2.25F,2.25F,1);g.renderItem(Items.PLAYER_HEAD.getDefaultInstance(),0,0);g.pose().popPose();}
    @Override protected void renderLabels(GuiGraphics g,int mx,int my){var s=menu.snapshot();var p=s.selected();String name=menu.npc().getName().getString();g.drawString(font,name,190,41,GOLD,true);g.drawString(font,"Humano | "+s.current().name,190,59,TEXT,false);g.drawCenteredString(font,"Catalogo de profissoes",269,91,GOLD);g.drawCenteredString(font,p.name,458,96,GOLD);g.drawWordWrap(font,Component.literal(p.description),366,116,184,TEXT);g.drawString(font,"Categoria: "+p.category.name(),366,150,MUTED,false);g.drawString(font,"Nivel: "+(s.current()==p?s.level():"-"),366,166,TEXT,false);g.drawString(font,"Experiencia: "+(s.current()==p?s.experience()+" / "+s.needed():"-"),366,180,TEXT,false);if(s.current()==p&&s.needed()>0){g.fill(366,194,548,201,0xFF0B0D10);g.fill(368,196,368+Math.round(178*s.experience()/(float)s.needed()),199,0xFFD5A83B);}g.drawString(font,"Aptidao: "+translateAptitude(s.aptitude()),366,207,TEXT,false);g.drawString(font,"Estacao: "+p.station(),366,221,TEXT,false);g.drawString(font,"Vinculo: "+s.station(),366,235,TEXT,false);g.drawString(font,"Ferramenta: "+p.tool(),366,249,TEXT,false);g.drawCenteredString(font,s.blocked(),458,264,p.implemented?GOLD:0xFF888888);g.drawCenteredString(font,"Selecione uma profissao para ver os requisitos",W/2,326,MUTED);}
    private static String translateAptitude(String a){return switch(a){case"LOW"->"Baixa";case"HIGH"->"Alta";default->"Media";};}private void panel(GuiGraphics g,int x,int y,int w,int h){x+=leftPos;y+=topPos;g.fill(x,y,x+w,y+h,0xE8191B1E);outline(g,x,y,w,h,0xFF8A6B32);}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){g.fill(0,0,width,height,0x99000000);int lx=(int)Math.round(toX(mx)),ly=(int)Math.round(toY(my));g.pose().pushPose();g.pose().translate(width/2F,height/2F,0);g.pose().scale(scale,scale,1);g.pose().translate(-width/2F,-height/2F,0);super.render(g,lx,ly,pt);renderTooltip(g,lx,ly);g.pose().popPose();}@Override public boolean mouseClicked(double x,double y,int b){return super.mouseClicked(toX(x),toY(y),b);}@Override public boolean mouseReleased(double x,double y,int b){return super.mouseReleased(toX(x),toY(y),b);}private double toX(double x){return width/2D+(x-width/2D)/scale;}private double toY(double y){return height/2D+(y-height/2D)/scale;}private static void outline(GuiGraphics g,int x,int y,int w,int h,int c){g.fill(x,y,x+w,y+1,c);g.fill(x,y+h-1,x+w,y+h,c);g.fill(x,y,x+1,y+h,c);g.fill(x+w-1,y,x+w,y+h,c);}
    private static final class PButton extends AbstractButton{private final Runnable action;private final boolean selected;PButton(int x,int y,int w,int h,Component t,Runnable a,boolean s){super(x,y,w,h,t);action=a;selected=s;}@Override public void onPress(){action.run();}@Override protected void renderWidget(GuiGraphics g,int mx,int my,float pt){int bg=selected?0xEE765115:isHoveredOrFocused()?0xEE514124:0xE52A2B2D;g.fill(getX(),getY(),getX()+width,getY()+height,bg);outline(g,getX(),getY(),width,height,selected?0xFFFFC44F:0xFF756F65);var f=Minecraft.getInstance().font;String text=getMessage().getString();float s=Math.min(1,(width-8F)/Math.max(1,f.width(text)));g.pose().pushPose();g.pose().translate(getX()+4,getY()+(height-8*s)/2,0);g.pose().scale(s,s,1);g.drawString(f,text,0,0,active?TEXT:0xFF777777,false);g.pose().popPose();}@Override protected void updateWidgetNarration(NarrationElementOutput o){defaultButtonNarrationText(o);}}
}
