package com.sam.realmfolk.content.item;

public enum UtilityAction {
    SETTLEMENT_CHARTER,
    SETTLEMENT_LEDGER,
    FAMILY_REGISTER,
    RESIDENCE_DEED,
    CONSTRUCTION_BLUEPRINT,
    SURVEYORS_ROD,
    BUILDER_HAMMER,
    WORK_CONTRACT,
    WORK_ORDER_BOOK,
    LEADERS_SEAL,
    GUARD_HORN,
    GUARD_BADGE,
    HEALER_SATCHEL,
    WEDDING_RING,
    SIMPLE_GIFT,
    WOODEN_TOY,
    FAMILY_CERTIFICATE
}
